process_pending_bookings:
  # run every 15 minutes
  cron: "*/15 * * * *"
  description: "Process pending bookings via cron for all events"
  class: "PendingBookingRakeWrapperJob"
  queue: "process_pending_bookings"